// Package vendoring puts a fixed version of the runtime into the project.
//
// A pinned clone rather than a machine path: the hooks call Python ultraloom,
// every project should say which version that is, and an upgrade should be a
// visible step. wiki_gate.py drifted in two of three repos because nothing
// wrote the version down.
package vendoring

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/xidus90/ultra-loom/internal/tomlstr"
)

// Runner is git, injected so the tests need no network and no repository.
//
// A real implementation runs the git executable with argv as its arguments --
// the word "git" itself is not part of argv -- in the directory dir, and
// returns git's standard output alone. Standard error belongs in the returned
// error, not in the string: the caller parses that string as a commit id, and
// a progress line mixed into it would be recorded as the pin. The output is
// returned raw -- trimming is the caller's business, and it does trim. A
// non-nil error means git did not run or exited non-zero; the string is then
// ignored. dir must already exist; creating it is not the runner's job, and a
// missing one is an error like any other.
type Runner func(dir string, argv ...string) (string, error)

// VendorDir is where the runtime lands, relative to the project root.
const VendorDir = ".ultraloom/vendor/ultraloom"

// Clone fetches the runtime at ref and reports the commit it actually got.
//
// Two shapes of pin, because git honours only one of them cheaply: a branch or
// tag can be had with a shallow `--branch` clone, while a commit id cannot --
// `--branch` resolves refs and nothing else, so a full SHA would be reported as
// a branch that does not exist. Such a ref gets a full clone and a detached
// checkout instead: slower, but it is the case a version pin is really for, and
// fetching a bare SHA needs a server setting no project can rely on.
//
// On failure Clone leaves whatever git left. It holds nothing but the Runner,
// so it can neither see nor remove a half-written clone inside someone else's
// project; the caller owns the target directory and owns cleaning it up.
func Clone(run Runner, root, url, ref string) (string, error) {
	// A ref reaches git as argv, where a leading dash is an option wherever it
	// stands -- `--upload-pack=...` is a command, not a version.
	if ref == "" || strings.HasPrefix(ref, "-") {
		return "", fmt.Errorf("refusing the ref %q: it must not be empty or start with a dash", ref)
	}
	// The destination stays relative, so git resolves it against the same
	// directory it is run in. An absolute one would be read against root here
	// and against the process cwd two lines down -- with a relative root those
	// are two different places, and the second one does not exist.
	dest := filepath.FromSlash(VendorDir)
	target := filepath.Join(root, dest)
	// `--` because a url is argv too: without it a `--upload-pack=...` posing
	// as a repository is a command git runs.
	if isCommitID(ref) {
		if _, err := run(root, "clone", "--", url, dest); err != nil {
			return "", fmt.Errorf("cloning %s: %w", url, err)
		}
		if _, err := run(target, "checkout", "--detach", ref); err != nil {
			return "", fmt.Errorf("checking out %s: %w", ref, err)
		}
	} else if _, err := run(root, "clone", "--depth", "1", "--branch", ref, "--", url, dest); err != nil {
		return "", fmt.Errorf("cloning %s at %s: %w", url, ref, err)
	}
	// The full id, not `--short`: an abbreviation is a prefix that grows
	// ambiguous as the repository does, and this is the value a later sync
	// compares against.
	commit, err := run(target, "rev-parse", "HEAD")
	if err != nil {
		return "", fmt.Errorf("reading the cloned commit: %w", err)
	}
	commit = strings.TrimSpace(commit)
	if commit == "" {
		return "", fmt.Errorf("git named no commit for %s", ref)
	}
	return commit, nil
}

// isCommitID recognises what git would resolve as an object name rather than a
// ref. Abbreviations count from git's own minimum of four; a branch that reads
// like one loses nothing, because the full clone resolves branch names too.
func isCommitID(ref string) bool {
	if len(ref) < 4 || len(ref) > 40 {
		return false
	}
	for _, r := range ref {
		if !strings.ContainsRune("0123456789abcdefABCDEF", r) {
			return false
		}
	}
	return true
}

// InstalledTOML is what a later `ultraloom sync` reads to know what init did.
//
// It cannot fail: every value is escaped rather than rejected, so there is no
// input for which it would have to return an error instead of a file.
func InstalledTOML(ref, commit, answersHash string, created []string) string {
	var body strings.Builder
	body.WriteString("# generated by `ultraloom init` -- do not edit\n" +
		"# init skips a file that is already here, this one included, so a\n" +
		"# second run cannot update the pin below. Only `ultraloom sync` will,\n" +
		"# and it does not exist yet.\n\n[vendor]\n")
	fmt.Fprintf(&body, "ref    = %s\ncommit = %s\n\n[answers]\nsha256 = %s\n\n[created]\n",
		tomlstr.Quote(ref), tomlstr.Quote(commit), tomlstr.Quote(answersHash))
	names := sorted(created)
	if len(names) == 0 {
		body.WriteString("files = []\n")
		return body.String()
	}
	body.WriteString("files = [\n")
	for _, name := range names {
		fmt.Fprintf(&body, "  %s,\n", tomlstr.Quote(name))
	}
	body.WriteString("]\n")
	return body.String()
}

// sorted makes the file a function of what was installed, not of the order the
// writer happened to finish in: this file is committed, and a diff that moves
// lines around on every run is a diff nobody reads. The caller's slice is left
// alone -- it is not ours to reorder.
func sorted(created []string) []string {
	names := make([]string, len(created))
	copy(names, created)
	sort.Strings(names)
	out := names[:0]
	for i, name := range names {
		if i == 0 || name != names[i-1] {
			out = append(out, name)
		}
	}
	return out
}
